### ISSUE TITLE
Install fails with build error.

### ISSUE THREAD

**Issue by blackdogdevelopers** [PrototypeInteractive/gatsby-react-boilerplate#12]
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/c/Users/Dave/Documents/Projects/testing/node_modules/node-gyp/lib
/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/home/dave/.nvm/versions/node/v12.16.2/bin/node" "/mnt/c/Users/Dave/Documents/Projects/testing/
node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "
--libsass_library="
gyp ERR! cwd /mnt/c/Users/Dave/Documents/Projects/testing/node_modules/node-sass
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any
"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any
"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!

npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dave/.npm/_logs/2020-04-19T02_44_09_878Z-debug.log

 ERROR

Command failed with exit code 1: npm install

  Error: Command failed with exit code 1: npm install

[2020-04-19T02_44_09_878Z-debug.log](https://github.com/PrototypeInteractive/gatsby-react-boilerplate/files/4498274/2020-04-19T02_44_09_878Z-debug.log)

**Comment by accaplan** [comment]
Any resolution on this? experiencing the same...
